[toolchain]
channel = "1.89"
components = ["clippy", "rustfmt", "rust-analyzer", "rust-src"]

targets = [
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
  "x86_64-unknown-linux-gnu",
  "aarch64-unknown-linux-gnu",
]
profile = "default"
